/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAttendanceRouteImport } from './routes/app/attendance'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppContractsRouteImport } from './routes/app/contracts'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppGuardsRouteImport } from './routes/app/guards'
import { Route as AppIncidentsRouteImport } from './routes/app/incidents'
import { Route as AppOperationsRouteImport } from './routes/app/operations'
import { Route as AppPatrolsRouteImport } from './routes/app/patrols'
import { Route as AppPayrollRouteImport } from './routes/app/payroll'
import { Route as AppProfitabilityRouteImport } from './routes/app/profitability'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGuardsRoute = AppGuardsRouteImport.update({
  id: '/guards',
  path: '/guards',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOperationsRoute = AppOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatrolsRoute = AppPatrolsRouteImport.update({
  id: '/patrols',
  path: '/patrols',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfitabilityRoute = AppProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/billing': typeof AppBillingRoute
  '/app/clients': typeof AppClientsRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/guards': typeof AppGuardsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/patrols': typeof AppPatrolsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profitability': typeof AppProfitabilityRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/billing': typeof AppBillingRoute
  '/app/clients': typeof AppClientsRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/guards': typeof AppGuardsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/patrols': typeof AppPatrolsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profitability': typeof AppProfitabilityRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/billing': typeof AppBillingRoute
  '/app/clients': typeof AppClientsRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/guards': typeof AppGuardsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/patrols': typeof AppPatrolsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profitability': typeof AppProfitabilityRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/attendance'
    | '/app/billing'
    | '/app/clients'
    | '/app/contracts'
    | '/app/documents'
    | '/app/guards'
    | '/app/incidents'
    | '/app/operations'
    | '/app/patrols'
    | '/app/payroll'
    | '/app/profitability'
    | '/app/schedule'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/attendance'
    | '/app/billing'
    | '/app/clients'
    | '/app/contracts'
    | '/app/documents'
    | '/app/guards'
    | '/app/incidents'
    | '/app/operations'
    | '/app/patrols'
    | '/app/payroll'
    | '/app/profitability'
    | '/app/schedule'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/attendance'
    | '/app/billing'
    | '/app/clients'
    | '/app/contracts'
    | '/app/documents'
    | '/app/guards'
    | '/app/incidents'
    | '/app/operations'
    | '/app/patrols'
    | '/app/payroll'
    | '/app/profitability'
    | '/app/schedule'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/guards': {
      id: '/app/guards'
      path: '/guards'
      fullPath: '/app/guards'
      preLoaderRoute: typeof AppGuardsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/operations': {
      id: '/app/operations'
      path: '/operations'
      fullPath: '/app/operations'
      preLoaderRoute: typeof AppOperationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/patrols': {
      id: '/app/patrols'
      path: '/patrols'
      fullPath: '/app/patrols'
      preLoaderRoute: typeof AppPatrolsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profitability': {
      id: '/app/profitability'
      path: '/profitability'
      fullPath: '/app/profitability'
      preLoaderRoute: typeof AppProfitabilityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBillingRoute: typeof AppBillingRoute
  AppClientsRoute: typeof AppClientsRoute
  AppContractsRoute: typeof AppContractsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppGuardsRoute: typeof AppGuardsRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppOperationsRoute: typeof AppOperationsRoute
  AppPatrolsRoute: typeof AppPatrolsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppProfitabilityRoute: typeof AppProfitabilityRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppBillingRoute: AppBillingRoute,
  AppClientsRoute: AppClientsRoute,
  AppContractsRoute: AppContractsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppGuardsRoute: AppGuardsRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppOperationsRoute: AppOperationsRoute,
  AppPatrolsRoute: AppPatrolsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppProfitabilityRoute: AppProfitabilityRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
